[build]
  publish = "dist" # This is the folder where your Vue.js project outputs the built files
  command = "npm run build" # Command to build your Vue.js app

[[redirects]]
  from = "/*" # Match all routes
  to = "/index.html" # Serve the index.html for SPA routing
  status = 200